name: Build libs

on:
  workflow_dispatch:

jobs:
  build-episodic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build episodic
      run: |
        ./deploy96.sh episodic 1.04 "Half-Life 2 EP1,2"
    - uses: actions/upload-artifact@v3
      with:
        name: episodic-android
        path: ./srceng-mod-launcher/bin
        if-no-files-found: error

  build-hl2mp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build hl2mp
      run: |
        ./deploy96.sh hl2mp 1.04 "Half-Life 2: Deathmatch" extras_dir.vpk 3
    - uses: actions/upload-artifact@v3
      with:
        name: hl2mp-android
        path: ./srceng-mod-launcher/bin
        if-no-files-found: error

  build-hl1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build hl1
      run: |
        ./deploy96.sh hl1 1.04 "Half-Life: Source" extras_dir.vpk 4
    - uses: actions/upload-artifact@v3
      with:
        name: hls-android
        path: ./srceng-mod-launcher/bin
        if-no-files-found: error

  build-cstrike:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build cstrike
      run: |
        ./deploy96.sh cstrike 1.07 "Counter-Strike: Source" extras_dir.vpk 7
    - uses: actions/upload-artifact@v3
      with:
        name: css-android
        path: ./srceng-mod-launcher/bin
        if-no-files-found: error

  build-portal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build portal
      run: |
        ./deploy96.sh portal 1.03 "Portal" extras_dir.vpk 5
    - uses: actions/upload-artifact@v3
      with:
        name: portal-android
        path: ./srceng-mod-launcher/bin
        if-no-files-found: error

  build-dod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build DoD
      run: |
        ./deploy96.sh dod 1.04 "Day of Defeat: Source" extras_dir.vpk 6
    - uses: actions/upload-artifact@v3
      with:
        name: dod-android
        path: ./srceng-mod-launcher/bin
        if-no-files-found: error
